"""Claude-owned environment switches and OTLP configuration selectors."""

ENABLE_TELEMETRY = "CLAUDE_CODE_ENABLE_TELEMETRY"
ENABLE_TRACES = "CLAUDE_CODE_ENHANCED_TELEMETRY_BETA"
DETAILED_TRACES = "ENABLE_BETA_TRACING_DETAILED"
DETAILED_ENDPOINT = "BETA_TRACING_ENDPOINT"
OTLP_PREFIX = "OTEL_EXPORTER_OTLP"

TRACES_EXPORTER = "OTEL_TRACES_EXPORTER"
