import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const manifest = JSON.parse(await readFile(new URL('spec/semconv.json', root), 'utf8'));
const license = await readFile(new URL('LICENSE', root), 'utf8');
const check = process.argv.includes('--check');
const constants = {
  CONTRACT_VERSION: manifest.contractVersion,
  SEMCONV_VERSION: manifest.semconvVersion,
  SCHEMA_URL: manifest.schemaUrl,
  ...manifest.attributes,
  INTEGRATIONS: manifest.integrations,
  TRACE_ATTRIBUTES: Object.fromEntries(Object.values(manifest.attributes)
    .filter((value) => value.startsWith('confident.trace.'))
    .map((value) => [value.slice('confident.trace.'.length), value])),
  SPAN_ATTRIBUTES: Object.fromEntries(Object.values(manifest.attributes)
    .filter((value) => value.startsWith('confident.span.'))
    .map((value) => [value.slice('confident.span.'.length), value])),
  REQUEST_ATTRIBUTES: Object.fromEntries(Object.values(manifest.attributes)
    .filter((value) => value.startsWith('gen_ai.request.'))
    .map((value) => [value.slice('gen_ai.request.'.length), value])),
};
const outputs = {
  'typescript/LICENSE': license,
  'typescript/src/semconv/generated.ts': '// Generated by scripts/sync-shared.mjs. Do not edit.\n\n' +
    Object.entries(constants).map(([key, value]) => `export const ${key} = ${JSON.stringify(value)} as const;`).join('\n') + '\n',
};
for (const [path, value] of Object.entries(outputs)) {
  const url = new URL(path, root);
  if (check) {
    const actual = await readFile(url, 'utf8').catch(() => undefined);
    if (actual !== value) {
      console.error(`Shared file out of date: ${fileURLToPath(url)}`);
      process.exitCode = 1;
    }
  } else {
    await writeFile(url, value);
  }
}
