"""Generate SDK constants and release compatibility docs from shared data.

Run with --check in CI. Uses only Python's standard library; never downloads data.
"""

import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def identifier(value):
    return re.sub(r"[^A-Za-z0-9]+", "_", value).upper()


def render(registry, release):
    lines = [
        '"""Generated by tools/generate_genai.py; do not edit.',
        "",
        "Known values are suggestions, not validation allowlists.",
        "Upstream OpenTelemetry semantic conventions, Apache-2.0.",
        '"""',
        "",
        f"SEMCONV_VERSION = {registry['version']!r}",
        f"SCHEMA_URL = {registry['schema_url']!r}",
        "",
    ]
    for key, attr in registry["attributes"].items():
        lines.append(f"{identifier(key)} = {key!r}")
        if isinstance(attr.get("type"), dict):
            for member in attr["type"].get("members", []):
                lines.append(
                    f"{identifier(key)}__{identifier(member['id'])} = {member['value']!r}"
                )
    code = "\n".join(lines) + "\n"
    docs = [
        "# Python release compatibility",
        "",
        "<!-- Generated by tools/generate_genai.py; edit the release manifest. -->",
        "",
        f"## {release['version']}",
        "",
        f"GenAI semantic conventions: **{registry['version']}** (development).",
        "",
        f"Schema URL: `{registry['schema_url']}`.",
        "",
        f"Registry SHA-256: `{release['registry_sha256']}`.",
        "",
        f"Package-owned instrumentation version: **{release['version']}**. No bundled third-party instrumentors.",
        "",
        f"Content: {release['content_representation']}",
        "",
        "| Dependency | Supported | Locally tested |",
        "|---|---|---|",
    ]
    for key, entry in release["dependencies"].items():
        docs.append(f"| {key} | {entry['supported']} | {', '.join(entry['tested'])} |")
    docs += [
        "",
        "## Instrumentation coverage",
        "",
        "| Integration | Operations | Validation |",
        "|---|---|---|",
    ]
    for item in release["instrumentation"]:
        docs.append(f"| {item['name']} | {item['surfaces']} | {item['validation']} |")
    docs += ["", "## Deviations and boundaries", ""]
    docs += [f"- {item}" for item in release["deviations"]]
    docs += [
        "",
        "For automatic instrumentation versus existing OTel spans, see [integration guide](integrations.md).",
        "",
    ]
    return code, "\n".join(docs)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--base", help="Git base revision: existing snapshots must be immutable"
    )
    args = parser.parse_args()
    if args.base and set(args.base) != {"0"}:
        subprocess.run(
            ["git", "rev-parse", "--verify", f"{args.base}^{{commit}}"],
            cwd=ROOT,
            capture_output=True,
            check=True,
        )
        previous_paths = subprocess.run(
            ["git", "ls-tree", "-r", "--name-only", args.base, "--", "spec/genai"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.splitlines()
        for name in previous_paths:
            if not name.endswith(".json"):
                continue
            path = ROOT / name
            previous = subprocess.run(
                ["git", "show", f"{args.base}:{name}"],
                cwd=ROOT,
                capture_output=True,
                check=True,
            ).stdout
            if not path.exists() or previous != path.read_bytes():
                raise SystemExit(f"Existing snapshot is immutable: {name}")
    release = json.loads((ROOT / "spec/releases/python-0.1.0.json").read_text())
    path = ROOT / "spec/genai" / (release["genai_version"] + ".json")
    raw = path.read_bytes()
    registry = json.loads(raw)
    assert hashlib.sha256(raw).hexdigest() == release["registry_sha256"], (
        "Registry hash mismatch"
    )
    for source in registry["sources"].values():
        assert (
            hashlib.sha256(source["text"].encode()).hexdigest() == source["sha256"]
        ), "Source hash mismatch"
    source_hash = hashlib.sha256(
        json.dumps(
            {key: value["sha256"] for key, value in registry["sources"].items()},
            sort_keys=True,
            separators=(",", ":"),
        ).encode()
    ).hexdigest()
    assert source_hash == registry["upstream"]["source_checksum_sha256"]
    code, doc = render(registry, release)
    outputs = {
        ROOT / "python/src/confident_trace/_genai.py": code,
        ROOT / "python/docs/compatibility.md": doc,
    }
    for path, data in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != data:
                raise SystemExit(f"Stale generated file: {path.relative_to(ROOT)}")
        else:
            path.write_text(data)


if __name__ == "__main__":
    main()
